<?php
$apiKey="rzp_test_FPgs3nlZNIlL5w";
include('connection.php');
session_start();    
$session=$_SESSION['id'];
$sqlii="SELECT register.loginid,register.fname,register.email,register.phone,register.phone,register.adress,register.id,order_tbl.id,order_tbl.price,order_tbl.login_id from order_tbl join register on order_tbl.login_id=register.loginid where register.loginid='$session'";
$result = mysqli_query($con, $sqlii);
while ($rows = mysqli_fetch_array($result)) {
    $vi=$rows['fname'];
    $ar=$rows['id'];
    $re=$rows['email'];
    $rw=$rows['phone'];



 }
$sr="SELECT SUM(price) FROM order_tbl where order_tbl.login_id='$session' and status='unpaid'";
$tt=mysqli_query($con,$sr);
while ($rows = mysqli_fetch_array($tt)) {
   // $id= $row['id'];
    $amount=$rows['SUM(price)'];
    // $name=$row['name'];

}
?>
<form method="POST" action="pay.php?amount=<?php echo $amount; ?>&&ar=<?php echo $ar; ?>">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $amount * 100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="<?php rand(100000, 999999);?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay Amount"
    data-name="E-farm"
    data-description="Add more colors to your day"
    data-image=""
    data-prefill.name="<?php echo $vi;?>"
    data-prefill.email="<?php echo $re;?>"
    data-prefill.contact="<?php echo $rw;?>"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
<!-- <input type="hidden" name="artist" value="<?php echo $ar; ?>">
<input type="hidden" name="amount" value="<?php echo $amount; ?>"> -->
</form>
<script>

  setTimeout(() => {

    document.getElementsByClassName('razorpay-payment-button')[0].click();

  }, 500);

</script>